FLASK_APP="app"
FLASK_DEBUG=False
FLASK_RUN_HOST="0.0.0.0"
FLASK_RUN_PORT=5000

FLASK_FAVICON_CACHE_SIZE=256
FLASK_FAVICON_CACHE_TTL=3600

FLASK_K8S_ANNOTATION_PREFIX="kubeboard.xyz"

FLASK_CONFIGURATION_SCHEMA=".schemas/configuration.schema.json"
FLASK_CONFIGURATION_FILE="kubeboard.yaml"
