stages:
  - security
  - lint
  - tests
  - build
  - cve
  - publish

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - scheduler_failure
      - stuck_or_timeout_failure
      - api_failure
      - job_execution_timeout
      - data_integrity_failure

variables:
  REGISTRY_URL: "registry.home.chupin.xyz"
  BUILDAH_VERSION: "latest"
  HADOLINT_VERSION: "latest-debian"
  TRIVY_VERSION: "latest"
  GITLEAKS_VERSION: "latest"
  HELM_VERSION: "latest"
  SKOPEO_VERSION: "latest"
  ALPINE_VERSION: "3"

  TRIVY_SEVERITY: HIGH,CRITICAL

  IMAGE_NAME: "${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"

  IGNORE_TRIVY_CVE: false

  RESULTS_FOLDER: results

include:
  - local: .gitlab/build.yml
    rules:
      - if: "$CI_COMMIT_TAG == null"
  - local: .gitlab/release.yml
    rules:
      - if: $CI_COMMIT_TAG
