security:gitleaks:
  stage: security
  image:
    name: "${REGISTRY_URL}/paas/zricethezav/gitleaks:${GITLEAKS_VERSION}"
    entrypoint: [""]
  before_script:
    - gitleaks version
  script:
    - gitleaks dir --follow-symlinks -v -f junit -r gitleaks-report.xml
  artifacts:
    paths:
      - gitleaks-report.xml
    reports:
      junit: gitleaks-report.xml


lint:dockerfile:hadolint:
  stage: lint
  image: "${REGISTRY_URL}/paas/hadolint/hadolint:${HADOLINT_VERSION}"
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile


lint:dockerfile:trivy:
  stage: lint
  image: "${REGISTRY_URL}/paas/aquasec/trivy:${TRIVY_VERSION}"
  before_script:
    - trivy --version
    # Downloading template format from Github
    - wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl -O junit.tpl
  script:
    # Fail on specified vulnerabilities
    - trivy config Dockerfile --exit-code 1 --severity "$TRIVY_SEVERITY" --format template --template "@junit.tpl" -o junit-report.xml
  artifacts:
    paths:
      - junit-report.xml
    reports:
      junit: junit-report.xml


lint:helm:
  stage: lint
  image: "${REGISTRY_URL}/paas/alpine/helm:${HELM_VERSION}"
  before_script:
    - helm version
  script:
    - helm lint chart


lint:python:black:
  stage: lint
  image: "${REGISTRY_URL}/paas/pipelinecomponents/black:${BLACK_VERSION}"
  script:
    - black --check --color --diff app
    - black --check --color --diff tests


lint:pip:licenses:
  stage: lint
  image: "${REGISTRY_URL}/paas/alpine:${ALPINE_VERSION}"
  before_script:
    - apk add --no-cache python3 py3-pip
    - python3 -m pip install --no-cache-dir --break-system-packages licensecheck
    - python3 -V
  script:
    - python3 -m licensecheck -r requirements.txt -l apache-2.0 -f html -o pip-licenses.html
    - python3 -m licensecheck -r requirements.txt -l apache-2.0 --zero --only-licenses $LICENSES_ALLOWED -f ansi
  artifacts:
    paths:
      - pip-licenses.html
  rules:
    - if: '$IGNORE_LICENSES_CHECK=="true"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  retry: 2


tests:pytest:
  stage: tests
  image: "${REGISTRY_URL}/paas/alpine:${ALPINE_VERSION}"
  before_script:
    - apk add --no-cache python3 py3-pip graphviz
    - python3 -m pip install --no-cache-dir --break-system-packages --no-deps -r requirements.txt
    - python3 -m pip install --no-cache-dir --break-system-packages -r tests/requirements.txt
    - python3 -V
    - python3 -m pytest -V
  script:
    - |
      python3 -m pytest tests \
        --retries 2 --retry-delay 5 --profile --profile-svg \
        --cov --cov-report "html:${RESULTS_FOLDER}/coverage" --cov-report "xml:${RESULTS_FOLDER}/coverage.xml" \
        --junit-xml="${RESULTS_FOLDER}/pytest-${CI_COMMIT_SHORT_SHA}.xml" \
        --html="${RESULTS_FOLDER}/pytest-${CI_COMMIT_SHORT_SHA}.html"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - "${RESULTS_FOLDER}"
      - "prof"
    reports:
      junit: "$RESULTS_FOLDER/pytest-${CI_COMMIT_SHORT_SHA}.xml"
      coverage_report:
        coverage_format: cobertura  # or jacoco
        path: ${RESULTS_FOLDER}/coverage.xml
    expire_in: 2 hour
    when: always
  retry: 2


build:docker:buildah:
  stage: build
  image: "${REGISTRY_URL}/paas/buildah/stable:${BUILDAH_VERSION}"
  before_script:
    - buildah version
  script:
    - buildah --storage-driver vfs bud --build-arg BUILD_DATETIME="$(date --rfc-3339=seconds | sed 's/ /T/')" -t "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" .
    - buildah --storage-driver vfs push -f v2s2 "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
  retry: 2


deploy:helm:
  stage: deploy
  image: "${REGISTRY_URL}/paas/alpine/helm:${HELM_VERSION}"
  before_script:
    - helm version
  script:
    - helm upgrade --install --create-namespace --set "image.repository=${IMAGE_NAME}" --set "image.tag=${CI_COMMIT_SHORT_SHA}" --wait --wait-for-jobs --timeout "$HELM_TIMEOUT" -n "$HELM_NAMESPACE" "$HELM_RELEASE" chart
  after_script:
    - helm uninstall -n "$HELM_NAMESPACE" "$HELM_RELEASE"


cve:docker:trivy:
  stage: cve
  image:
    name: "${REGISTRY_URL}/paas/aquasec/trivy:${TRIVY_VERSION}"
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  before_script:
      - trivy --version

      # Downloading template format from Github
      - wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl -O junit.tpl

      # Update vuln db
      - trivy clean --scan-cache
      - trivy --cache-dir .trivycache/ image --download-db-only --no-progress
  script:
      # Fail on specified vulnerabilities
      - |
        trivy image \
          --exit-code 1 \
          --severity "$TRIVY_SEVERITY" \
          --no-progress \
          --scanners vuln \
          --format template \
          --template "@junit.tpl" \
          -o junit-report.xml \
          "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
  cache:
      paths:
      - .trivycache/
  artifacts:
      paths:
          - junit-report.xml
      reports:
          junit: junit-report.xml
  rules:
    - if: '$IGNORE_TRIVY_CVE=="true"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success


cve:helm:trivy:
  stage: cve
  image:
    name: "${REGISTRY_URL}/paas/aquasec/trivy:${TRIVY_VERSION}"
    entrypoint: [""]
  before_script:
      - trivy --version

      # Downloading template format from Github
      - wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl -O junit.tpl

      # Update vuln db
      - trivy clean --scan-cache
      - trivy --cache-dir .trivycache/ image --download-db-only --no-progress
  script:
      # Fail on specified vulnerabilities
      - |
        trivy config \
          --exit-code 1 \
          --ignorefile .trivyignore.yaml \
          --severity "$TRIVY_SEVERITY" \
          --format template \
          --template "@junit.tpl" \
          -o junit-report-helm.xml \
          chart
  cache:
      paths:
      - .trivycache/
  artifacts:
      paths:
          - junit-report-helm.xml
      reports:
          junit: junit-report-helm.xml
  rules:
    - if: '$IGNORE_TRIVY_CVE=="true"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success


post:docker:clean:
  stage: .post
  image: "${REGISTRY_URL}/paas/myifeng/quay.io_skopeo_stable:${SKOPEO_VERSION}"
  before_script:
    - skopeo -v
  script:
    - skopeo delete "docker://${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
  allow_failure: true
  when: on_failure
